### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by bripkens** [aaronshaf/react-toggle#100]
Would be great if you could release the latest changes to make sure that react-toggle is compatible with React 16. Thanks!

**Comment by jshimko** [comment]
Yes please!  Super :( about the relentless Proptype console logs!

**Comment by adrianojdesouza** [comment]
Hi guys, any news about new release?

**Comment by aaronshaf** [comment]
Would this be a major release? Thoughts?

**Comment by aaronshaf** [comment]
Done. 4.0.1 now (major, and then an immediate patch). 

Anyone interested in joining the list of npm owners / the release team?

**Comment by adrianojdesouza** [comment]
Thanks @aaronshaf

**Comment by bripkens** [comment]
I'd be open to this @aaronshaf.

**Comment by bripkens** [comment]
and thank you for the release!

**Comment by aaronshaf** [comment]
@bripkens Done. You're now both a trusted collaborator (see invites) and fellow npm owner.
