### ISSUE TITLE
Toggle causes onClick handlers in parent to be called twice

### ISSUE THREAD

**Issue by broofa** [aaronshaf/react-toggle#103]
Use toggle inside a DOM structure that has an onClick handler. E.g.:
```
<label onClick={alert}>
  <Toggle />
  <span>Some Text</span>
</label>
```

Click outside the Toggle - e.g. on the span = one alert (as expected)
Clicking on the Toggle = *two* alerts

I believe the issue is that in addition to expected event bubbling, Toggle is [generating a second event](https://github.com/aaronshaf/react-toggle/blob/3575b51350c2e81d624b3adcc6863db97d3f1bb2/src/component/index.js#L36). 
 Inserting `event.stopPropagation()` around [line 34](https://github.com/aaronshaf/react-toggle/blob/3575b51350c2e81d624b3adcc6863db97d3f1bb2/src/component/index.js#L36) fixes the problem. 

Edit: Note that because this is generating two *distinct* events there isn't a simple way to ignore one of the events.  ☹️

**Comment by bradennapier** [comment]
Yeah I am running into this as well.  I dont want to use the onclick of react-toggle itself and send it readOnly yet the event still occurs twice.

**Comment by bradennapier** [comment]
@broofa I built a flow-based fork of this which also fixes the issue

https://github.com/Dash-OS/react-toggle-2

```
yarn add react-toggle-2
```

**Comment by nivnahmias** [comment]
Would love to see a fix for this issue...

**Comment by broofa** [comment]
Pretty clearly not gonna get fixed.  Am tired of seeing this in my issues list.
