### ISSUE TITLE
FastClick breaks react-toggle

### ISSUE THREAD

**Issue by jedwards1211** [aaronshaf/react-toggle#22]
So I just started testing my app with toggles on an iPad using FastClick to get rid of the 300ms click delay.  It turns out FastClick somehow breaks react-toggle (it wouldn't toggle when tapped), and I assume it's because of the call to `checkbox.click()`.  I disabled FastClick on the toggles by giving them (and subcomponents) the `needsclick` class, but then, of course, they suffer from the 300ms click delay as before.

Given this, one can imagine the toggle might not work correct on other strange devices/environments.

Once realizing that the problem would be solved if I removed the checkbox altogether, I got to thinking, is the hidden checkbox really that necessary?  I suppose it's nice to get the same `event` in an `onChange` handler as you'd get from a checkbox, so that you can just use toggles as a drop-in replacement for checkboxes.  But even so, if we got rid of the checkbox we could still program the toggle to pass a fake event object with at least a `value` property to the `onChange`  handler.

**Comment by aaronshaf** [comment]
If we could maintain accessibility using aria roles and aria states and use an `<input type='hidden'>` then perhaps we could get rid of the hidden checkbox.

**Comment by aaronshaf** [comment]
Retitled this issue to focus on FastClick breakage.

**Comment by aaronshaf** [comment]
Can someone else confirm this is an issue? Or explain why exactly FastClick would cause problems with the component?

**Comment by aaronshaf** [comment]
Looks like FastClick is no longer needed for newest Safari on iOS or Chome on Android.
