### ISSUE TITLE
Feature request: optional additional class(es) on component

### ISSUE THREAD

**Issue by thom-nic** [aaronshaf/react-toggle#31]
It would be nice if `Toggle` took a prop of additional classNames to add to the base component.  This would support things like e.g. making different color toggles (`.react-toggle.blue`) or different sizes (`.react-toggle.big`).  So my toggle would look like 

```
 <Toggle classNames={'blue big'} ... />
```

In order to accomplish the same thing now I'd have to create a wrapper with the classes and my styles would have to all use `!important` to override the existing definitions.

**Comment by bnadeau** [comment]
I added that as part of PR #30 a few days ago, but I'll break it out into a separate PR to make it simpler to merge.

**Comment by thom-nic** [comment]
Oh very cool - I am using a classed wrapper and `!important` styles for now but I'll watch that PR so I know when to update.  Thanks!
