### ISSUE TITLE
Use CSS preprocessor

### ISSUE THREAD

**Issue by omgaz** [aaronshaf/react-toggle#35]
Query/Feature Request.

```
+ This can be really handy for consolidating meaning into seemingly magic hex.
+ Great way of allowing extensions.
- Complicates the stack with yet another dependency
- No standard pre-processor; do you use scss, sass, stylus etc…
```

If this is of any interest to the direction of the project I could look at opening a PR. Alternatively, completely understandable if you'd rather take the KISS approach.

**Comment by BDiehr** [comment]
Given the scope of the project (An awesome toggle) and the amount of CSS (which  is probably about as much css as this project will ever have) I don't think a preprocessor is appropriate unfortunately.
