### ISSUE TITLE
invariant.js:39Uncaught Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs.

### ISSUE THREAD

**Issue by ejabu** [aaronshaf/react-toggle#42]
invariant.js:39Uncaught Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs.

What should I do ?
I have React-Select also on my module.

**Comment by ejabu** [comment]
resolve: {
        alias: {
            react: path.resolve('./node_modules/react')
        },
    }

This solve Issues, but CSS is not loaded

**Comment by guilhermedecampo** [comment]
@ejamuh how you handled this issue ?

**Comment by harvitronix** [comment]
+1

**Comment by bryant-sharethis** [comment]
+1

**Comment by ahstro** [comment]
Looks like this is fixed and merged, just not published. I'll look into publishing a new version to npm this week.
