### ISSUE TITLE
Unknown DOM property fill-rule

### ISSUE THREAD

**Issue by sungwoncho** [aaronshaf/react-toggle#44]
_Version_
- react-toggle 2.1.0
- React 15.1.0.

_Problem_

When I use react-toggle, I get an error:

```
Warning: Unknown DOM property fill-rule. Did you mean fillRule
```

I don't get the error when I remove react-toggle from my component.

**Comment by dbishai** [comment]
I am having the same problem with React 15.2.1.

**Comment by basarat** [comment]
Same with React 15.3.0 :rose:

**Comment by basarat** [comment]
Its been fixed : https://github.com/aaronshaf/react-toggle/commit/4a08ad9e42cf19088351b708f77d10ed8122aa71#diff-94c6a8ca320f0c61238334c2575f6be7L10

**Comment by basarat** [comment]
Update to `2.1.1` and its fixed on NPM as well :heart:
