### ISSUE TITLE
Looking for collaborators

### ISSUE THREAD

**Issue by aaronshaf** [aaronshaf/react-toggle#50]
Anyone interested?

**Comment by BDiehr** [comment]
I'm interested in helping maintain if you're looking for someone

**Comment by aaronshaf** [comment]
@BDiehr Still interested?

**Comment by BDiehr** [comment]
@aaronshaf Still interested! I'm using this package for my applications I work on and would love to help maintain it/handle upgrading it to newer versions of react

**Comment by aaronshaf** [comment]
Awesome, please check your e-mail for the invite!

**Comment by aaronshaf** [comment]
It'd be nice to have one more collaborator. Anyone else interested?

**Comment by ahstro** [comment]
I was asked to be a collaborator in [this comment](https://github.com/aaronshaf/react-toggle/pull/57#issuecomment-251222544), but I figured we should keep the conversation in here?

What does being a collaborator entail, more specifially? Should I be closing issues and merging PRs? I don't want to overstep any boundries :angel:

**Comment by aaronshaf** [comment]
Closing issues, merging PRs, pushing releases to NPM (with semver). I just added you on NPM.

**Comment by ahstro** [comment]
Okay :) I'll do my best.
