### ISSUE TITLE
Change file structure

### ISSUE THREAD

**Issue by ahstro** [aaronshaf/react-toggle#58]
As it is now, the structure of this project feels a bit chaotic, with almost everything living in the root.
I would like to move things into subdirectoris, so that we have a file structure that looks more like this:

```
src/
  x.js
  check.js
  index.js
  index.html
  style.css
dist/
  bundle.js
  index.html
  style.css
docs/
  index.html
  style.css
LICENSE
README.md
package.json
webpack.config.js
.gitignore
.npmignore
```

Now, I'm not particularly familiar with all files in the project yet, but you (hopefully) get the gist of it :)
Basically, we would have everything that will be compiled into the module in `src`, the compiled bundle in `build` (this is what npm and `docs` will use), `docs` will contain what is now split between the `examples` subdirectory and the `gh-pages` branch - i.e., the documentation where people can see the module in action and what people can use to test it out when developing.

If this sounds okay, I can get on it (after merging some PRs so they don't have to rebase), otherwise, just close this. @aaronshaf

**Comment by aaronshaf** [comment]
👍
