### ISSUE TITLE
Add linting

### ISSUE THREAD

**Issue by ahstro** [aaronshaf/react-toggle#61]
I noticed there were some discrepancies in the syntax being used, so I propose we add linting into the development mix, what do you think @aaronshaf?

I nominate my favorite combo: [ESLint](http://eslint.org/) plus [standardjs](http://standardjs.com/)'s [sharable config](https://github.com/feross/eslint-config-standard). We're already not using semicolons for the most part, so we've already passed the biggest hurdle people see with standardjs. :innocent:

**Comment by aaronshaf** [comment]
I love standard 👍

**Comment by ahstro** [comment]
Then it's settled 😊

**Comment by ahstro** [comment]
Closed by #62
