### ISSUE TITLE
Version control of bundles/dist

### ISSUE THREAD

**Issue by ahstro** [aaronshaf/react-toggle#63]
Should the compiled bundles really be version controlled? AFAIK, this makes for a messy git history as well as inaccurate diffs (I have 20k+ additions already :cold_sweat:  ).

I'm not sure how this works with npm, it was a long time since I published there. Also, not tracking them would prevent people from using the repo directly in their `package.json`-files.

Maybe we should just commit the compiled files when we're releasing a new veresion? Or maybe there's a way to not track it at all but include it in releases/on npm somehow?

**Comment by ahstro** [comment]
I really should read before I write.. Just found this on the [npm docs](https://docs.npmjs.com/cli/publish)

> All files in the package directory are included if no local **.gitignore**  or **.npmignore**  file exists. If both files exist and a file is ignored by **.gitignore** but not by **.npmignore** then it will be included.

So I'm guessing just add `dist/` to `.gitignore` but not to `.npmignore` and we'll be fine?

That still doesn't let people use the repo as a direct source, but I'm okay with that if you are?

**Comment by ahstro** [comment]
Hmm, just remembered that it also doesn't solve the bundle in `/docs/`..

**Comment by aaronshaf** [comment]
I recommend against this. bundles/dist should have only the version represented in package.json.

**Comment by ahstro** [comment]
Wait, against using version control or against not using version control? (Sorry about my wall of ramblings)

I think we should:
- Remove `dist` from GitHub
- Add `dist` and `docs/bundle.js*` to `.gitignore`
- Create a `prepublish` npm script that
  1. Builds the bundles
  2. Force adds `docs/bundle.js*` to git (so the demo only ever has the latest **published** version, i.e. the one in `package.json`)

If I understood your comment correctly, I think you agree, but I'm not 100% sure :sweat_smile:

**Comment by aaronshaf** [comment]
I definitely agree to your list 👍

**Comment by ahstro** [comment]
Great :smile:
