### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by ahstro** [aaronshaf/react-toggle#68]
I've setup testing and added a few tests, but we still need to improve the coverage a lot.

I ran into some trouble when trying to test the actual click/toggle functionality (which is a _pretty_ big part of the component). Using Enzyme's `.simulate('click')` doesn't seem to propagate properly; this is a known issue with their shallow rendering, but it also doesn't seem to work with full DOM rendering.

If anyone wants to give this a shot, that'd be great, just let me know and I'll assign you; otherwise, I'm going to try to get to this when I have time. :)

**Comment by vvvdeep** [comment]
Hey @ahstro , just created a PR #104 .
This being my first ever PR, let me know if I missed something.
