### ISSUE TITLE
Why does installing this also install react-addons-pure-render-mixin?

### ISSUE THREAD

**Issue by zeroasterisk** [aaronshaf/react-toggle#72]
```
├─┬ react-toggle@2.1.1
│ └── react-addons-pure-render-mixin@15.3.2
```

It looks like this [is now legacy](https://facebook.github.io/react/docs/pure-render-mixin.html).

I don't find mention of it in the package.json... 

what's up?

**Comment by ahstro** [comment]
That was a dependency for version 2.1.1, we have since moved to using `react-addons-shallow-compare`, but, now that I think about it, I guess we should move to using `React.PureComponent`.

**Comment by mgan59** [comment]
Yeah this is causing all kinds of errors in my deployment now :|
