### ISSUE TITLE
Updated version to 2.2.1 breaks my app?

### ISSUE THREAD

**Issue by ghost** [aaronshaf/react-toggle#88]
```
index.js:37Uncaught TypeError: Super expression must either be null or a function, not undefined(…)
```
I guess its got something PureComponent change recently.

**Comment by ahstro** [comment]
I'm guessing you need to update React to >15.3.0, sorry about this

**Comment by ghost** [comment]
I downgraded the version to 2.01 and still see this error so I guess this wasn't your fault. Need to find out what package is causing this. Thanks.
